### ISSUE TITLE
Missing pieces when importing

### ISSUE THREAD

**Issue by donchuan3d** [cuddlyogre/ExportLDraw#14]
So far very cool addon! but for some reason there are some pieces missing, which I can see in the library, so they should be there, but for some reason they are not included in the import. Any idea what could be the issue?

**Comment by cuddlyogre** [comment]
Would you be willing to share the file?

**Comment by donchuan3d** [comment]
@cuddlyogre woops I am really sorry, mistake was from my side. I am using LDD and exporting as LDraw file. And although these pieces where in the LDraw library and in LDD as well, they were missing in the ldraw export file, therefore they were not been written in the ldraw file at all.
