### ISSUE TITLE
Empty collections on import

### ISSUE THREAD

**Issue by AlexFundorin** [cuddlyogre/ExportLDraw#15]
Tried importing mpd files in both 2.9.2 (clean, portable) and 3.0.0 alpha (daily driver). 
Both apps are importing empty collections with an empty object at 3d cursor.
https://i.imgur.com/edOmvSw.png
Models from this thread, for example - https://forums.ldraw.org/thread-20769.html
Import settings were left as default.

P.S. offtopic question: I downloaded some models in lcd format. They can be opened in LeoCAD. How do I properly import them in Blender?

**Comment by cuddlyogre** [comment]
Yes that's happening here too. I'll look into it as soon as I can.

**Comment by cuddlyogre** [comment]
Ldraw path filled in:
![image](https://user-images.githubusercontent.com/3506795/120357964-9d693700-c2cb-11eb-83f3-93cc2a0d9710.png)

Missing Ldraw path
![image](https://user-images.githubusercontent.com/3506795/120358089-c093e680-c2cb-11eb-9399-58b43890f2b0.png)

Make sure your ldraw path is set before importing. The method I use to find it is rather simple and won't autofill the path it if it's not where it looks.

It looks like I need to make it clear to the user when the ldraw path wasn't set and to improve the process for finding it.

**Comment by AlexFundorin** [comment]
Mine was located in d:\%something&\ldraw. Solved. Thank you.

![](https://i.imgur.com/E2IpCqk.png)

What about the lcd files, like the ones that can be found in here? https://www.marutan.net/arcsite/lego/
Should I resave them, one by one, to a compatible format, using LeoCAD?

**Comment by cuddlyogre** [comment]
At first glance those files don't look like they're saved in the ldraw format and if that's the case they'll need to be converted. I'll have to do more research to see what I can do on my end.

**Comment by AlexFundorin** [comment]
It seems like it's an outdated format. https://github.com/leozide/leocad/issues/68
Thanks for the plugin, btw. Brings back memories.

**Comment by AlexFundorin** [comment]
I wish that the plugin would remember ldraw path. Yes, it's possible to add a preset, but there's no way to make it default, now.

**Comment by AlexFundorin** [comment]
For some reason, I'm getting empty imports again. 

![](https://i.imgur.com/NpFNivY.png)

**Comment by AlexFundorin** [comment]
My bad. I've added a path to ldraw installation folder this time, instead of the parts folder.

**Comment by cuddlyogre** [comment]
I'll work on saving previous settings next. It's been brought up more than once and would be a nice feature to have.
