### ISSUE TITLE
Installation steps

### ISSUE THREAD

**Issue by mjhorvath** [cuddlyogre/ExportLDraw#20]
Could you describe in the readme how to install the tool for those of us who don't use Blender frequently? Thanks.

**Comment by OllyJ918** [comment]
What I did was clone the repo, put it into a zip file then in blender EDIT->preferences->Add ons->install addon-> click zipped file then it will show in File-> import/export and then you'll need to put in your ldraw path into the first path of the file explorer that opens within blender :)

**Comment by aefferenpriv** [comment]
I did above. Problem I have is that the .mpd file is only imported as group and not as collection. So the file breakdown shows at the right in the Scene Collection. But on the canvas/main screen nothing shows. What is it I do wrong.
As stated I am also using Blender very infrequently. Help is much appreciated.
