### ISSUE TITLE
Colored Trans materials are too opaque

### ISSUE THREAD

**Issue by MilanV** [cuddlyogre/ExportLDraw#23]
Hi Matthew, this is a continuation of [ldraw forum topic]([https://forums.ldraw.org/thread-24153-post-44009.html#pid44009), hopefully it will be more visible and maintained this way.

My setup is blender 2.82 (on Linux), current ExportLDraw plugin (cf23105aa2), Cycles render engine.
Material in test is LDraw Material 40 Tran_Black Alt. As an example, I used this view of excavator cabin with Trans Black windows, under quite strong light. With no modification it renders like this:
![orig](https://user-images.githubusercontent.com/3765741/146691834-2a81089d-8be5-4071-adc2-b39c392eb42f.png)

As an experiment, I raised a value of the material color in the LEGO Transparent shader to 0.913 and the render looks better then but I do not know if this is the correct way how to fix this issue:
![improved](https://user-images.githubusercontent.com/3765741/146691894-a05bdf22-f0cc-4f4b-aac2-45c0ec6cd0f8.png)

**Comment by cuddlyogre** [comment]
I'll see what I can do. The values are pulled straight from ldcfgalt and looks good in Eevee. I might have to add a Cycles specific material.

**Comment by cuddlyogre** [comment]
I've push a tweak to the plastic/glass material. Please do a test import and let me know what you think.

This is what some of the colors looks like in my testing now. The top cubes are trans blue and the trans black you are having trouble with.
![untitled](https://user-images.githubusercontent.com/3506795/146722027-a5e04fb1-7d9b-4c2a-84e2-314f4285db72.png)

**Comment by MilanV** [comment]
Thank you for looking at this.
It might be I have something configured wrong because eevee is useless for me as well. Yes, there are some hard-to-see shadows behind trans-black window so it is not opaque completely but the graphics is unnatural. That's more visible when I made the window more transparent, using the same technique as above.

I looked at tips at Blender Maker site. They recommend having Render > Light Paths > Reflective/Refractive Caustics turned on and increasing the number of light bounces for Transparency and Transmission. As far as I can see both settings are available for Cycles renderer only, I used them both while making test renders above. For eevee I cannot see any tip so I used default settings and this is the result:
Orig:
![eevee_orig](https://user-images.githubusercontent.com/3765741/146721051-7a2f3142-cc56-464a-aae5-408248f70ca1.png)

Trans-Black more transparent:
![eevee_improved](https://user-images.githubusercontent.com/3765741/146721086-2a1bbbc9-fcbc-482e-8838-3cea34f8f951.png)

And, as another issue, eevee renders some subfiles as covered with pink curtain :)

**Comment by MilanV** [comment]
Ah, a mid-air collision :) What renderer you used? It looks really good.

**Comment by MilanV** [comment]
Ah, sorry for a little delay, it took me a while to make some tests, I hoped to find some configuration tips for eevee as well.

Your new commit made the situation much better! Result for cycles is quite good, I'd say. Eevee is still unnatural but also much better than before. It is a question what configuration of eevee renderer is needed to get correct result. Do you have any tip I should try?

Otherwise, I think we can close this issue because the improvement is really good. Thanks a lot!

Cycles:
![newcommit_cycles](https://user-images.githubusercontent.com/3765741/146727780-c023e126-02ca-47ca-a2bd-615150150d4a.png)

Eevee:
![newcommit_eevee](https://user-images.githubusercontent.com/3765741/146727807-69d20783-4101-4e81-930c-d4954fc650f7.png)
