### ISSUE TITLE
Add precision to exported edges

### ISSUE THREAD

**Issue by fhareide** [cuddlyogre/ExportLDraw#25]
In _ldraw_export.py_ I think you should change line 273 
from:
`line.append(__fix_round(vv))`
to
`line.append(__fix_round(vv, precision))`

If not the lines will be off if the precision is changed before export.

**Comment by cuddlyogre** [comment]
Done! https://github.com/cuddlyogre/ExportLDraw/commit/852743203c352830da5a4baf4b7f524651e03a6f
