### ISSUE TITLE
Feature Request: A Bevel Option When Importing

### ISSUE THREAD

**Issue by LookItsJawn** [cuddlyogre/ExportLDraw#26]
Was hoping an option for beveling the bricks on import could be added, similar to TobyLobster's importer. :)

**Comment by cuddlyogre** [comment]
I originally removed the bevel option because when logos are imported with bevel on, the logos are deformed. I suppose there's no harm in adding it back so long as I warn that logos might not show properly.

**Comment by cuddlyogre** [comment]
Added in the most recent release.
