### ISSUE TITLE
`ldraw_export_polygons` not recognised

### ISSUE THREAD

**Issue by zed0** [cuddlyogre/ExportLDraw#27]
Thanks for all your work on this, editing textures in Blender before and exporting for PartDesigner is a lot easier than trying to use decals in PartDesigner.

## Bug
I had a bit of trouble getting this working because it would always output an almost empty file. Eventually I tracked this down to it not recognising the `ldraw_export_polygons` properties I had set up.

I'm not sure why the original wasn't working, but I managed to get it working by making the following change to the code:
```diff
diff --git a/ldraw_export.py "b/C:\\Users\\zed0\\AppData\\Roaming\\Blender Foundation\\Blender\\2.92\\scripts\\addons\\ExportLDraw-2022-07-31-00\\ldraw_export.py"
index ce32c82..558360c 100644
--- a/ldraw_export.py
+++ "b/C:\\Users\\zed0\\AppData\\Roaming\\Blender Foundation\\Blender\\2.92\\scripts\\addons\\ExportLDraw-2022-07-31-00\\ldraw_export.py"
@@ -63,7 +63,7 @@ def do_export(filepath):
         if obj.users < 1:
             continue

-        if obj.ldraw_props.export_polygons:
+        if obj.get('ldraw_export_polygons'):
             polygon_obj_names.append(obj.name)
         else:
             subfile_obj_names.append(obj.name)
```

These are the properties I had set up on my object:
![image](https://user-images.githubusercontent.com/416354/183254143-e9131a29-dd27-49e7-8587-dd76245430c3.png)
These are the colours:
![image](https://user-images.githubusercontent.com/416354/183254274-334b23a8-28ae-4ec0-a569-49d649741a72.png) ![image](https://user-images.githubusercontent.com/416354/183254291-4a2f5c60-9af5-4b45-a78e-2183c6d85a32.png)

These are the options I was exporting with:
![image](https://user-images.githubusercontent.com/416354/183254634-488aa053-4727-4f6c-83fa-a1c378c72578.png)

I'm using ExportLDraw 2022-07-31-00 release of and Blender 2.92.0.

## Final images
Once I'd made the change mentioned above I did eventually manage to get it exported into PartDesigner, so here are some images if you're interested:
![image](https://user-images.githubusercontent.com/416354/183254423-7c92fedd-26d5-4847-8bff-e61fa61910ab.png) ![image](https://user-images.githubusercontent.com/416354/183254479-a8e293a7-ab54-4fac-b843-f9a7b6565302.png)

**Comment by cuddlyogre** [comment]
Hi! Thanks for the kind words. That model you're working on looks very familiar...

Please redownload the most recent release. The release you downloaded originally was incomplete, and I'm still figuring out github.

The fixed release has an easier to use LDraw panel that sets a lot of these attributes for you on objects. I still have to figure out a good way to do it for materials.

**Comment by zed0** [comment]
Thanks, I've re-downloaded the latest release, but am still having the same issue.

> The fixed release has an easier to use LDraw panel that sets a lot of these attributes for you on objects. I still have to figure out a good way to do it for materials.

How do I access this panel? I'm not very familiar with Blender. I've been setting the object properties manually based on those in the export example.

**Comment by cuddlyogre** [comment]
Maybe there's a caching hiccup going on. I've created a fresh release of the current master branch.
https://github.com/cuddlyogre/ExportLDraw/releases/tag/2022-08-07-00

The new panel:
![image](https://user-images.githubusercontent.com/3506795/183293002-b13c3361-de1d-45f8-99ca-e41c5fd8eef8.png)

When you have an object selected, you can view and change several LDraw properties of that object. When there are no objects selected, you are able to set the LDraw properties of the scene. Currently, that is not being used, but I have plans for it.

**Comment by zed0** [comment]
Ah, not being familiar with Blender I hadn't discovered this panel. It was hidden on my view like this:
![image](https://user-images.githubusercontent.com/416354/183314084-0df8b5ab-6c6e-449f-82e6-dde221283687.png)

Ticking the Export Polygons box on there works fine with the previous version, thanks!

If I don't tick export polygons does that mean it gets used as an outline in Studio/PartDesigner?

**Comment by cuddlyogre** [comment]
Any object not marked as "Export polygons" will be exported as line type 1 using whatever values are in "Color code" and "Filename". This allows you to use empties as placeholders if you don't want to import the part into your scene for whatever reason.

If you choose "Export polygons" on an item that isn't a mesh, nothing will be exported. This is more of an interface oversight that I'm working on at the moment.
