### ISSUE TITLE
[Bug] Error/crash when importing ldr/mpd files

### ISSUE THREAD

**Issue by xXDudeMcDudeXx** [cuddlyogre/ExportLDraw#28]
Trying to import any model either crashes blender or throws "TypeError: cannot unpack non-iterable NoneType object." Not sure what I am doing wrong. Fresh install of blender 3.2.2
Both the LDraw parts path, and Studio 2.0 path give the same error.

LDraw path: C:\Users\USER\Documents\Parts Library\ldraw
Studio path: C:\Program Files\Studio 2.0\ldraw

Here are the models I attempted to use. They all open using LDView.
[Models.zip](https://github.com/cuddlyogre/ExportLDraw/files/9331197/Models.zip)

Here are the debug logs generated by Blender after trying to load each of the models.
[blender_debug_output.txt](https://github.com/cuddlyogre/ExportLDraw/files/9331206/blender_debug_output.txt)
[blender_system_info.txt](https://github.com/cuddlyogre/ExportLDraw/files/9331207/blender_system_info.txt)

**Comment by cuddlyogre** [comment]
Removed original comment.

Very strange. I'll look into it.

**Comment by cuddlyogre** [comment]
There was a bug when BFC processing was turned off. Please install the newest release.

https://github.com/cuddlyogre/ExportLDraw/releases/tag/2022-08-13-00

Just a heads up. The models in your bug report will have missing parts if your LDraw library path is set to the official LDraw library.

**Comment by xXDudeMcDudeXx** [comment]
Thanks for the quick update. Only one of the models I attempted seems to not work. I figure that is an issue with the file itself but I will provide the error log just incase. Otherwise my original issue has been resolved. Thanks again for this awesome tool.

The new release only imports a section of the model but throws this new error.
Edit: It is the Classicistic Villa.ldr model
[blender_debug_output.txt](https://github.com/cuddlyogre/ExportLDraw/files/9332374/blender_debug_output.txt)

**Comment by cuddlyogre** [comment]
You have a few parts with color code 1009022. What color is that supposed to be? When it's converted to hex it comes out to #f657e which isn't a valid hex value.

**Comment by cuddlyogre** [comment]
I've fixed the new error you found. It's in this new release.

https://github.com/cuddlyogre/ExportLDraw/releases/tag/2022-08-13-01

**Comment by xXDudeMcDudeXx** [comment]
I found the colors that they should be incase you still want that.
part 2654 should be Trans clear (47)
part 3062b should be reddish brown (70)
part 3626c should be Light Bluish Gray (71)
part 6141 doesn't exist?
Edit: Found codes, found new part
