### ISSUE TITLE
Parts Don't Tumble in Physics Simulation

### ISSUE THREAD

**Issue by ekohlwey** [cuddlyogre/ExportLDraw#31]
Hi there!

I was trying your plugin out today and found that the imported parts don't tumble in a rigid body simulation, even if the shape is set to mesh or convex hull (or anything else for that matter). Bounce, for example does work properly though.

I'm at somewhat of a loss of how to provide a better report since I'm not much of a blender user, but happy to do some legwork if you have ideas.

**Comment by cuddlyogre** [comment]
In my testing, it has to do with the part being parented to the normal and the scale. It looks like the physics simulation sees the part as multiple km in size.

I was able to get it to work by unchecking the circled items when you import. 
![image](https://user-images.githubusercontent.com/3506795/221015627-f8825968-99e0-4b2d-8dab-b0b90c78738a.png)

You may be able to get away with just unchecking the parent to empty item.
![image](https://user-images.githubusercontent.com/3506795/221017234-4c382a47-17b3-40a2-b145-57614189237d.png)

With the part(s) imported, apply the scale.

Then select the part, go to the physics properties, and check rigid body. I also added a collision plane with rigid body on, with type passive.

![image](https://user-images.githubusercontent.com/3506795/221018229-b889e562-12f0-4d1c-b94f-0de665576ff6.png)
![image](https://user-images.githubusercontent.com/3506795/221018267-b48cb6b2-cb24-4645-b7e3-d2e71cc7ebce.png)
![image](https://user-images.githubusercontent.com/3506795/221018104-7220fbca-e7aa-4961-87a0-e0663343061a.png)

It seems I need to add options to set up rigid body on imported parts.

**Comment by ekohlwey** [comment]
Thanks! Unchecking those options and applying the scale worked as you recommended.

**Comment by markelwin** [comment]
Hello. Is this ticket considered closed? I am interested in implementing a good first issue on the repository to volunteer my time in exchange for learning how this software works. Please reach out to me if either of you are interested and I will follow up in email.
