### ISSUE TITLE
Parts not importing well in Blender 3.5

### ISSUE THREAD

**Issue by AllanJard** [cuddlyogre/ExportLDraw#35]
Hi! I'm interested in using this plug-in, but it doesn't seem to work in Blender 3.5.0 (I'm using OpenSUSE if that makes any difference).

I installed the plug-in by selecting the "Download zip" option in github and then installing it in Blender. The import option for LDraw .dat files shows up in the list, so I downloaded [part 3020](https://library.ldraw.org/library/official/parts/3020.dat) and selected that file to import. This is the result:

![image](https://user-images.githubusercontent.com/84905443/236608157-d012022d-a071-4eca-91ed-928a30dff58d.png)

It should be along these lines:

![image](https://user-images.githubusercontent.com/84905443/236608166-d69f7add-24cb-4221-a93b-13d9583cc3cd.png)

If there is any other information I can provide, please do just say!

**Comment by AllanJard** [comment]
Just tried Blender 3.4.1 with exactly the same result. I suspect I'm missing something?

**Comment by cuddlyogre** [comment]
I wasn't able to recreate the issue. It's possible you have an incomplete LDraw library.

Check the Blender console to see if there are mentions of missing files or errors.

**Comment by AllanJard** [comment]
Beautiful! I hadn't entered the path for the complete ldraw package into the import option for ldraw. I just over looked it - apologies.

Love it - thank you for this!
