### ISSUE TITLE
2458.dat doesn't import

### ISSUE THREAD

**Issue by elfprince13** [cuddlyogre/ExportLDraw#41]
`2458.dat` (Brick  1 x  2 with Pin) isn't importing and just leaves unsightly holes in my model. Any idea what's going on here?

**Comment by cuddlyogre** [comment]
https://github.com/cuddlyogre/ExportLDraw/releases/tag/2023-08-02-00

Please install this release. I accidentally pushed an experiment I was doing with studs to master.
