### ISSUE TITLE
export suggestion

### ISSUE THREAD

**Issue by sampotter123** [cuddlyogre/ExportLDraw#43]
can you add the ability to export only edges to dat (like ac3d ldraw export)

**Comment by cuddlyogre** [comment]
That should be possible. I'll look into it.

Just for my own curiosity, what is the intended usage for this?

**Comment by sampotter123** [comment]
> That should be possible. I'll look into it.
> 
> Just for my own curiosity, what is the intended usage for this?

thanks for you quick reply

to export 2d cross-section from blender to ldcad to use as a reference

**Comment by sampotter123** [comment]
thanks for adding it

**Comment by sampotter123** [comment]
I notice that i can't export, only edges (no faces).
are you still planning to add the requested feature?

**Comment by cuddlyogre** [comment]
I'll see what I can do.

**Comment by sampotter123** [comment]
> I'll see what I can do.
thanks
f.y.i "ac3d ldraw plugin" can export just edges

**Comment by sampotter123** [comment]
thanks
f.y.i "ac3d ldraw plugin" can export just edges

**Comment by cuddlyogre** [comment]
You used to be able to with mine, with some trickery, but a recent addition prevents it. I have to make a couple tweaks to enable it again.

When you say edges, are you referring to LDraw line types 2 and 5 or Blender mesh edges?

**Comment by sampotter123** [comment]
blender mesh edges

i want to be able too export from blender a cross-section (basically an edge loop, no polygons) from a 3d mesh, then import it to ldcad too use as a reference.

**Comment by cuddlyogre** [comment]
https://github.com/cuddlyogre/ExportLDraw/releases/tag/2023-10-02-00

To export edges, go into face select mode, select all, delete Just Faces, then go into edge select mode, select all, and Mark Sharp. Make sure the LDraw panel is properly filled in. Check "Export polygons", and export as normal.

![image](https://github.com/cuddlyogre/ExportLDraw/assets/3506795/785f2eef-e11b-448b-851a-2643d0fb5374)
