### ISSUE TITLE
Missing array dimension

### ISSUE THREAD

**Issue by trevorsandy** [cuddlyogre/ExportLDraw#44]
For the logo_choices import options:

```python
chosen_logo_choices = list(((logo, logo, logo) for logo in ["logo", "logo2", "logo3", "logo4", "logo5", "high-contrast"]))
```

The following line should be:
```python
ImportOptions.chosen_logo_choices[ImportOptions.chosen_logo][0]
```

https://github.com/cuddlyogre/ExportLDraw/blob/fc86febe402b720f83f0760899608fbf44300d02/import_options.py#L55

As it is, the returned default logo choice is:
```python
('logo3', 'logo3', 'logo3')`
```

Better still, the displayed user logo choices could be improved by suppressing the logo (line), and logo2 (outline) options which are not used. Also, the high-contrast option should not be used as it is specific to enhancing the 'instructions' look.

```python
    chosen_logo_choices = (
       #("logo", "Line", "Single line logo geometry"),
       #("logo2", "Outline", "Outlined logo geometry"),
        ("logo3", "Flattened", "Raised flat logo geometry"),
        ("logo4", "Rounded", "Raised rounded logo geometry"),
        ("logo5", "Subtle Rounded", "Subtle rounded logo geometry"),
    )
```

Cheers,

**Comment by cuddlyogre** [comment]
Thank you for the report. I've fixed it in the newest release.
