### ISSUE TITLE
Slope texture getting applied to whole brick

### ISSUE THREAD

**Issue by elfprince13** [cuddlyogre/ExportLDraw#45]
Notice how the slope 75 1 x 2 x 3 bricks on either forward prong are rough on the non-sloped portion of the brick:
![Red Planet Interceptor by elfprince13 on flickr](https://live.staticflickr.com/65535/53343249356_42869efd9e_k.jpg)

**Comment by cuddlyogre** [comment]
Sorry for taking so long to respond. The notification for your issue fell through the cracks.

What is the part number?
Are you willing to upload your model here so I can test?

**Comment by elfprince13** [comment]
It's a Slope 75 2 x 1 x 3 (4460). Not sure if `a` or `b` off the top of my head. However this may be a recent bug impact more parts as I also have recent (December 14) renders showing it impacting Slope 33 3 x 2 (3298), but older (October 10) renders do not have that problem on the same part.

**Comment by cuddlyogre** [comment]
I've imported every 75 part and I can't replicate this. 

Did you apply rotation on the object by chance? The shader uses angles and rotations of the mesh to determine where the slope texture should go. When I applied rotation on the object, I was then able to replicate this.

Are you willing to share the original LDraw model so that I can test it?

**Comment by elfprince13** [comment]
yes, in both cases the part is rotated.

**Comment by elfprince13** [comment]
oh, annoyingly the attachment didn't come through, stand by.

**Comment by elfprince13** [comment]
(hereby grant a license to use this model for testing + debugging of this Blender plugin, copyright 2023 Thomas Dickerson, all rights reserved)

[RedPlanetViper-Checked-Colored.ldr.zip](https://github.com/cuddlyogre/ExportLDraw/files/13952611/RedPlanetViper-Checked-Colored.ldr.zip)

**Comment by cuddlyogre** [comment]
![image](https://github.com/cuddlyogre/ExportLDraw/assets/3506795/ba99125b-25a0-4337-824c-027a1d6c523c)

I'm not able to replicate it going back to builds starting in November.

What versions of Blender and ExportLDraw are you using?

**Comment by elfprince13** [comment]
I have 2 machines - one with Blender 3.3.1 and one with 3.6.2. Both appear to have plugin version 2023-10-02 as their most recent.

**Comment by cuddlyogre** [comment]
I've been unable to replicate this so far. 

What does the shader node setup for that material look like in your blend file?
This is what it should look like.

![image](https://github.com/cuddlyogre/ExportLDraw/assets/3506795/dd7f94e7-6033-4b28-97f4-524700b5ffa7)

**Comment by elfprince13** [comment]
<img width="940" alt="Screenshot 2024-01-16 at 11 28 40 AM" src="https://github.com/cuddlyogre/ExportLDraw/assets/2703145/ad3ae521-b3f6-4334-8be6-d93d9b9d5f55">

looks right, afaict

**Comment by cuddlyogre** [comment]
What does the Transform panel look like?
![image](https://github.com/cuddlyogre/ExportLDraw/assets/3506795/8f63ac1a-44e3-4983-9326-d316487e7070)

**Comment by elfprince13** [comment]
![Screenshot 2024-01-16 at 3 06 43 PM](https://github.com/cuddlyogre/ExportLDraw/assets/2703145/fd3784a1-53ed-48c8-a7d3-9d93b57067e7)

**Comment by cuddlyogre** [comment]
Did you build this model in stud.io? The part names are sometimes not mapped properly to the official LDraw library.

I would really like to see the blend file if you're ok with that.

**Comment by elfprince13** [comment]
The model was built in BrickSmith, then fine-tuned in stud.io; however, the same issue appears in the version of the .blend which was imported directly from BrickSmith. Both versions are included in this zip. Shared under same terms as the .mpd file above.

[RedPlanetViper-blender.zip](https://github.com/cuddlyogre/ExportLDraw/files/13978306/RedPlanetViper-blender.zip)

**Comment by cuddlyogre** [comment]
At some point, a node in the slope texture shader was lost. To fix:

Go to shaders:
![image](https://github.com/cuddlyogre/ExportLDraw/assets/3506795/fc638582-cf92-441c-b52e-9cc764003041)

Select the sloped part and then the slope texture node group:
![image](https://github.com/cuddlyogre/ExportLDraw/assets/3506795/31602ed7-fb6c-4288-9339-a0b94e8bca06)

Selected the undefined node and hit X to delete it:
![image](https://github.com/cuddlyogre/ExportLDraw/assets/3506795/a8140014-6906-4a5b-8cc5-401f4f07bad1)

Add a Mix Color node in its place. Make sure the node doesn't intersect any of the lines or else they will be connected. Set up the connections like in the image.
![image](https://github.com/cuddlyogre/ExportLDraw/assets/3506795/afee7d0c-9157-4bbf-9f31-6dfff7adfbbb)

The texture will be applied properly.
![image](https://github.com/cuddlyogre/ExportLDraw/assets/3506795/a129a31f-a30c-4a4e-a20c-de221205c0bb)

**Comment by elfprince13** [comment]
super funky - thanks for debugging this! I appreciate not having to reimport the larger model where this cropped up.
