### ISSUE TITLE
when i export a object to ldr or dat nothing happens

### ISSUE THREAD

**Issue by Archviz360** [cuddlyogre/ExportLDraw#46]
when i export a object to ldr or dat nothing happens. 

i press on export and then choose a location and a name. then i also added the patth where Ldraw parts are and press on export. nothing happens. and no export happens. can nayone pls help me??

**Comment by cuddlyogre** [comment]
This is usually a sign that the header isn't filled out.

![image](https://github.com/cuddlyogre/ExportLDraw/assets/3506795/65a75411-8c50-452c-97b4-d9a2e4869feb)

**Comment by MAriehamn360-Vitrin2** [comment]
thanks :) it worked
