### ISSUE TITLE
Incorrect brick between studio and the importer

### ISSUE THREAD

**Issue by beetaa** [cuddlyogre/ExportLDraw#55]
Please take sometime to see [this model from bricklink](https://www.bricklink.com/_file/studio/downloadModel?idModel=112489), in bricklink this's shown as:

![image](https://github.com/cuddlyogre/ExportLDraw/assets/5688224/095d83b1-fe62-48c1-a021-691e33c9219d)

but after import to blender, it's as:

![image](https://github.com/cuddlyogre/ExportLDraw/assets/5688224/7c2145d6-ec69-46df-b641-69d300a048e5)

latest version of bricklink studio and importer are used. thank you.

**Comment by beetaa** [comment]
FYI, after trying several version of the importer, [v2024-01-22-00](https://github.com/cuddlyogre/ExportLDraw/releases/tag/2024-01-22-00) do it right, while all newer versions have the problems (no circle on top, or wrong brick direction).

**Comment by cuddlyogre** [comment]
I'll take a look and see what's going on.

**Comment by cuddlyogre** [comment]
I am able to import it correctly. Is it possible you have **No studs** checked and **Shade smooth** unchecked?

If not, it could be the import hitting an error somewhere.
What version of Blender are you using?
Are there any errors in your system console?

![image](https://github.com/cuddlyogre/ExportLDraw/assets/3506795/2865e937-3945-4368-9f7b-408a057b28f8)
![image](https://github.com/cuddlyogre/ExportLDraw/assets/3506795/54a69228-d08a-4cd9-98e5-0a9a7b02edb6)

**Comment by beetaa** [comment]
@cuddlyogre It works, just like you said, **have No studs checked and Shade smooth unchecked**, I use blender 4.1.1 and 4.0.2, they all work fine now. I will close this issue. thank you so much.
