### ISSUE TITLE
can any one help me to fix this error? 

### ISSUE THREAD

**Issue by Archviz360** [cuddlyogre/ExportLDraw#59]
is there any easy way to fix this error? 

![Skärmbild 2024-09-12 132038](https://github.com/user-attachments/assets/36ee5fe7-1e4d-4ec8-b330-76437c8ab312)

**Comment by cuddlyogre** [comment]
Would you be willing to provide the model so that I can troubleshoot the problem more easily?

**Comment by Archviz360** [comment]
i asked a blender group. it seems that blender havew changed a bit. its now clear that blender wants people only to do archviz or animation of non nostalgic things. i have asked bricklinks to make animation feature many times. they dont wants that feature. i also asked mecabrics before to make it possible to work offline without internet like bricklink studio they will never make it possible. its just to acept for me. my dream of making lego movies will never be reality. i cant learn blender its to hard for me to learn and all the other 3d softwares are only made for making general stuff like archviz or other animation. Some one told me to try lumion but lumion is only for archviz and it costs 4000 usd. Unreal engine never works and takes at least 600 GB of hard drive and then i got tips about twinmotion but twinmotion is not a software i would use. i used to be into archviz but not anymore.

**Comment by cuddlyogre** [comment]
If you're looking to do brickfilms with Blender, it's not terribly difficult when you come up with a process.
What are you trying to accomplish here? I may be able to assist.

**Comment by Archviz360** [comment]
sorry for late reply. I was trying to make the ramp to be able to rotate but waht i can see the pivot is set in the middle that causes the object to not rotate correct.

**Comment by cuddlyogre** [comment]
I'm putting together a little tutorial that should answer your question.

**Comment by cuddlyogre** [comment]
https://www.youtube.com/watch?v=jqYzXwT19ZU
Here's my approach. Let me know if you need any clarification.

**Comment by Archviz360** [comment]
il take a look at it.

**Comment by Archviz360** [comment]
thanks :) it worked. i got an idea. i saw a few month ago some one using walk and run cycle for lego figures. it was for mecabrics models. i think it would be great idea to add feature like walk cycle and run cycle in order to save time.

**Comment by cuddlyogre** [comment]
There is something like that already if you create your figures with
Leocad. I need to make the logic more generic so you can use other
programs.

**Comment by Archviz360** [comment]
how?

**Comment by cuddlyogre** [comment]
![image](https://github.com/user-attachments/assets/b7efbdaa-a408-4897-a126-b16d33c8bb51)
Select all that parts of your minifigure and click "Rig minifigure" in the LDraw panel.
I need to flesh it out more, but it should be functional.

**Comment by Archviz360** [comment]
thanks :)
