### ISSUE TITLE
tried to make an auto animation walk plugin.

### ISSUE THREAD

**Issue by Archviz360** [cuddlyogre/ExportLDraw#60]
I tried to make a blender plugin that would speedup walk and run animation process. every thing seems to work well the only problem is that im getting Thigh or shin bones not found in the armature. Please check bone names.
il give a link to my video https://www.youtube.com/watch?v=a0IYGvHriqM

**Comment by Archviz360** [comment]
![Skärmbild 2024-10-11 211104](https://github.com/user-attachments/assets/77350969-9f63-49a1-bfa9-fbe88b29c28e)
![Skärmbild 2024-10-11 211109](https://github.com/user-attachments/assets/c5466395-b11a-45a9-9a45-6b6b091d5f66)

**Comment by cuddlyogre** [comment]
I'd have to see the code to the script to know for sure. Do you have it uploaded somewhere?

**Comment by Archviz360** [comment]
can i have your email so i can send the file?

**Comment by Archviz360** [comment]
il try to upload it here on my github so you can acess it from my github.

**Comment by Archviz360** [comment]
update: i have solved the problem.
